name: Deploy to AWS App Runner

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-1           # 리전 수정
  ECR_REPOSITORY: helloworld           # ECR 리포지토리명
  IMAGE_TAG: ${{ github.sha }}
  APP_RUNNER_SERVICE_ARN: arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess # 미리 만들어둔 서비스 ARN

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image to ECR
        run: |
          IMAGE_URI=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Update App Runner service
        run: |
          aws apprunner update-service \
            --service-arn "${{ env.APP_RUNNER_SERVICE_ARN }}" \
            --source-configuration "ImageRepository={ImageIdentifier=${IMAGE_URI},ImageRepositoryType=ECR}" \
            --auto-deployments-enabled